__all__ = [
    'BaseParameters',
]
from toloka.client.primitives.base import BaseTolokaObject
from typing import (
    Any,
    Dict,
    Optional,
    overload
)

class BaseParameters(BaseTolokaObject):
    class Parameters(BaseTolokaObject):
        def __init__(self) -> None:
            """Method generated by attrs for class BaseParameters.Parameters.
            """
            ...

        _unexpected: Optional[Dict[str, Any]]

    def __init__(self, *, parameters: Optional[Parameters] = None) -> None:
        """Method generated by attrs for class BaseParameters.
        """
        ...

    _unexpected: Optional[Dict[str, Any]]
    parameters: Optional[Parameters]
