from toloka.client.primitives.base import BaseTolokaObject
from toloka.client.project.field_spec import FieldSpec
from toloka.client.project.template_builder.actions import (
    OpenLinkActionV1,
    PlayPauseActionV1,
    NotifyActionV1,
    OpenCloseActionV1,
    ToggleActionV1,
    SetActionV1,
    BulkActionV1,
    RotateActionV1
)
from toloka.client.project.template_builder.base import BaseComponent
from toloka.client.project.template_builder.conditions import (
    EmptyConditionV1,
    NotConditionV1,
    EqualsConditionV1,
    PlayedConditionV1,
    PlayedFullyConditionV1,
    RequiredConditionV1,
    SubArrayConditionV1,
    AllConditionV1,
    SchemaConditionV1,
    AnyConditionV1,
    LinkOpenedConditionV1
)
from toloka.client.project.template_builder.data import (
    InternalData,
    InputData,
    RelativeData,
    LocalData,
    OutputData
)
from toloka.client.project.template_builder.fields import (
    TextFieldV1,
    NumberFieldV1,
    GroupFieldOption,
    MediaFileFieldV1,
    CheckboxFieldV1,
    FileFieldV1,
    ListFieldV1,
    RadioGroupFieldV1,
    DateFieldV1,
    TextareaFieldV1,
    ImageAnnotationFieldV1,
    ButtonRadioFieldV1,
    ButtonRadioGroupFieldV1,
    PhoneNumberFieldV1,
    EmailFieldV1,
    SelectFieldV1,
    CheckboxGroupFieldV1
)
from toloka.client.project.template_builder.helpers import (
    SwitchHelperV1,
    TransformHelperV1,
    ConcatArraysHelperV1,
    IfHelperV1,
    ReplaceHelperV1,
    Object2EntriesHelperV1,
    TextTransformHelperV1,
    Entries2ObjectHelperV1,
    YandexDiskProxyHelperV1,
    SearchQueryHelperV1,
    JoinHelperV1
)
from toloka.client.project.template_builder.layouts import (
    BarsLayoutV1,
    SidebarLayoutV1,
    ColumnsLayoutV1,
    SideBySideLayoutV1
)
from toloka.client.project.template_builder.plugins import (
    TriggerPluginV1,
    HotkeysPluginV1,
    TolokaPluginV1
)
from toloka.client.project.template_builder.view import (
    ImageViewV1,
    DividerViewV1,
    MarkdownViewV1,
    VideoViewV1,
    DeviceFrameViewV1,
    ActionButtonViewV1,
    AlertViewV1,
    CollapseViewV1,
    LabeledListViewV1,
    LinkViewV1,
    GroupViewV1,
    ListViewV1,
    TextViewV1,
    AudioViewV1,
    IframeViewV1
)
from typing import (
    Tuple,
    List,
    Any,
    Dict,
    Union,
    Optional
)


class TemplateBuilder(BaseTolokaObject):
    def __init__(self, *, view: Optional[BaseComponent] = None, plugins: Optional[List[BaseComponent]] = None, vars: Optional[Dict[str, Any]] = None) -> None:
        """Method generated by attrs for class TemplateBuilder.
        """
        ...

    _unexpected: Optional[Dict[str, Any]]
    view: Optional[BaseComponent]
    plugins: Optional[List[BaseComponent]]
    vars: Optional[Dict[str, Any]]

def get_input_and_output(tb_config: Union[dict, TemplateBuilder]) -> Tuple[Dict[str, FieldSpec], Dict[str, FieldSpec]]: ...BulkActionV1 = BulkActionV1NotifyActionV1 = NotifyActionV1OpenCloseActionV1 = OpenCloseActionV1OpenLinkActionV1 = OpenLinkActionV1PlayPauseActionV1 = PlayPauseActionV1RotateActionV1 = RotateActionV1SetActionV1 = SetActionV1ToggleActionV1 = ToggleActionV1AllConditionV1 = AllConditionV1AnyConditionV1 = AnyConditionV1EmptyConditionV1 = EmptyConditionV1EqualsConditionV1 = EqualsConditionV1LinkOpenedConditionV1 = LinkOpenedConditionV1NotConditionV1 = NotConditionV1PlayedConditionV1 = PlayedConditionV1PlayedFullyConditionV1 = PlayedFullyConditionV1RequiredConditionV1 = RequiredConditionV1SchemaConditionV1 = SchemaConditionV1SubArrayConditionV1 = SubArrayConditionV1InputData = InputDataInternalData = InternalDataLocalData = LocalDataOutputData = OutputDataRelativeData = RelativeDataButtonRadioFieldV1 = ButtonRadioFieldV1GroupFieldOption = GroupFieldOptionButtonRadioGroupFieldV1 = ButtonRadioGroupFieldV1CheckboxFieldV1 = CheckboxFieldV1CheckboxGroupFieldV1 = CheckboxGroupFieldV1DateFieldV1 = DateFieldV1EmailFieldV1 = EmailFieldV1FileFieldV1 = FileFieldV1ImageAnnotationFieldV1 = ImageAnnotationFieldV1ListFieldV1 = ListFieldV1MediaFileFieldV1 = MediaFileFieldV1NumberFieldV1 = NumberFieldV1PhoneNumberFieldV1 = PhoneNumberFieldV1RadioGroupFieldV1 = RadioGroupFieldV1SelectFieldV1 = SelectFieldV1TextFieldV1 = TextFieldV1TextareaFieldV1 = TextareaFieldV1ConcatArraysHelperV1 = ConcatArraysHelperV1Entries2ObjectHelperV1 = Entries2ObjectHelperV1IfHelperV1 = IfHelperV1JoinHelperV1 = JoinHelperV1Object2EntriesHelperV1 = Object2EntriesHelperV1ReplaceHelperV1 = ReplaceHelperV1SearchQueryHelperV1 = SearchQueryHelperV1SwitchHelperV1 = SwitchHelperV1TextTransformHelperV1 = TextTransformHelperV1TransformHelperV1 = TransformHelperV1YandexDiskProxyHelperV1 = YandexDiskProxyHelperV1BarsLayoutV1 = BarsLayoutV1ColumnsLayoutV1 = ColumnsLayoutV1SideBySideLayoutV1 = SideBySideLayoutV1SidebarLayoutV1 = SidebarLayoutV1HotkeysPluginV1 = HotkeysPluginV1TriggerPluginV1 = TriggerPluginV1TolokaPluginV1 = TolokaPluginV1ActionButtonViewV1 = ActionButtonViewV1AlertViewV1 = AlertViewV1AudioViewV1 = AudioViewV1CollapseViewV1 = CollapseViewV1DeviceFrameViewV1 = DeviceFrameViewV1DividerViewV1 = DividerViewV1GroupViewV1 = GroupViewV1IframeViewV1 = IframeViewV1ImageViewV1 = ImageViewV1LabeledListViewV1 = LabeledListViewV1LinkViewV1 = LinkViewV1ListViewV1 = ListViewV1MarkdownViewV1 = MarkdownViewV1TextViewV1 = TextViewV1VideoViewV1 = VideoViewV1