__all__ = [
    'BaseData',
    'InputData',
    'InternalData',
    'LocalData',
    'LocationData',
    'OutputData',
    'RelativeData',
]
from toloka.client.project.template_builder.base import BaseComponent
from typing import (
    Any,
    Dict,
    Optional
)

class BaseData(BaseComponent):
    """Components used for working with data: input, output, or intermediate.
    """

    def __init__(
        self,
        path: Optional[Any] = None,
        default: Optional[Any] = None
    ) -> None:
        """Method generated by attrs for class BaseData.
        """
        ...

    _unexpected: Optional[Dict[str, Any]]
    path: Optional[Any]
    default: Optional[Any]


class InputData(BaseData):
    """The input data.

    For example, links to images that will be shown to users. In the Template Builder sandbox, you can
    set an example of input data.
    Attributes:
        path: Path to the property containing data. Dots are used as separators: path.to.some.element. To specify the
            path to the array element, specify its sequence number starting from zero, for example: items.0
        default: The value to be used as the default data. This value will be shown in the interface, so it might hide
            some placeholders, for example, in the field.text component.
    """

    def __init__(
        self,
        path: Optional[Any] = None,
        default: Optional[Any] = None
    ) -> None:
        """Method generated by attrs for class InputData.
        """
        ...

    _unexpected: Optional[Dict[str, Any]]
    path: Optional[Any]
    default: Optional[Any]


class InternalData(BaseData):
    """The data available only from within the task.

    This data is not saved to the results. Use this data to calculate or store intermediate values.
    Attributes:
        path: Path to the property containing data. Dots are used as separators: path.to.some.element. To specify the
            path to the array element, specify its sequence number starting from zero, for example: items.0
        default: The value to be used as the default data. This value will be shown in the interface, so it might hide
            some placeholders, for example, in the field.text component.
    """

    def __init__(
        self,
        path: Optional[Any] = None,
        default: Optional[Any] = None
    ) -> None:
        """Method generated by attrs for class InternalData.
        """
        ...

    _unexpected: Optional[Dict[str, Any]]
    path: Optional[Any]
    default: Optional[Any]


class LocalData(BaseData):
    """The local data available only from inside the component.

    This data is used in some auxiliary components, such as helper.transform.
    Attributes:
        path: Path to the property containing data. Dots are used as separators: path.to.some.element. To specify the
            path to the array element, specify its sequence number starting from zero, for example: items.0
        default: The value to be used as the default data. This value will be shown in the interface, so it might hide
            some placeholders, for example, in the field.text component.
    """

    def __init__(
        self,
        path: Optional[Any] = None,
        default: Optional[Any] = None
    ) -> None:
        """Method generated by attrs for class LocalData.
        """
        ...

    _unexpected: Optional[Dict[str, Any]]
    path: Optional[Any]
    default: Optional[Any]


class LocationData(BaseComponent):
    """This component sends the device coordinates

    To find out if the transmitted coordinates match the ones that you specified, use the conditions.DistanceConditionV1.
    """

    def __init__(self) -> None:
        """Method generated by attrs for class LocationData.
        """
        ...

    _unexpected: Optional[Dict[str, Any]]


class OutputData(BaseData):
    """The output data.

    This is what you get when you click the Send button.
    Attributes:
        path: Path to the property containing data. Dots are used as separators: path.to.some.element. To specify the
            path to the array element, specify its sequence number starting from zero, for example: items.0
        default: The value to be used as the default data. This value will be shown in the interface, so it might hide
            some placeholders, for example, in the field.text component.
    """

    def __init__(
        self,
        path: Optional[Any] = None,
        default: Optional[Any] = None
    ) -> None:
        """Method generated by attrs for class OutputData.
        """
        ...

    _unexpected: Optional[Dict[str, Any]]
    path: Optional[Any]
    default: Optional[Any]


class RelativeData(BaseData):
    """A special component for saving data.

    It's only available in the field.list component.
    Attributes:
        path: Path to the property containing data. Dots are used as separators: path.to.some.element. To specify the
            path to the array element, specify its sequence number starting from zero, for example: items.0
        default: The value to be used as the default data. This value will be shown in the interface, so it might hide
            some placeholders, for example, in the field.text component.
    """

    def __init__(
        self,
        path: Optional[Any] = None,
        default: Optional[Any] = None
    ) -> None:
        """Method generated by attrs for class RelativeData.
        """
        ...

    _unexpected: Optional[Dict[str, Any]]
    path: Optional[Any]
    default: Optional[Any]
