__all__ = [
    'Solution',
]
import typing


class Solution:
    """Performer response for one task

    Attributes:
        output_values: Dictionary "field name" - "response value", by the number of fields that should be in the response.
    """

    def __init__(self, output_values: typing.Dict[str, typing.Any]) -> None:
        """Method generated by attrs for class Solution.
        """
        ...

    output_values: typing.Dict[str, typing.Any]
