__all__ = [
    'Solution',
]
from typing import (
    Any,
    Dict
)

class Solution:
    """Performer response for one task

    Attributes:
        output_values: Dictionary "field name" - "response value", by the number of fields that should be in the response.
    """

    def __init__(self, output_values: Dict[str, Any]) -> None:
        """Method generated by attrs for class Solution.
        """
        ...

    output_values: Dict[str, Any]
